services:

  pg_java:
    build:
      dockerfile: ./docker/db.Dockerfile
      context: .
    image: vinnioh/pg_java
    container_name: pg_java
    ports:
      - "5432:5432"
    networks:
      - nwpicpay
    volumes:
      - pgdata:/var/lib/postgresql/data/

#  api-picpay:
#    build:
#      context: .
#      dockerfile: ./docker/api.Dockerfile
#    image: vinnieoh/api_picpay
#    container_name: api_picpay
#    ports:
#       - "8080:8080"
#    networks:
#       - nwpicpay
#    depends_on:
#      - "pg_java"

networks:
  nwpicpay:
    driver: bridge

volumes:
  pgdata: